apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: level
spec:
  params:
    - name: NAMESPACE
      default: brownbag
    - name:  IMAGE
  steps:
    - name: play
      image: $(params.IMAGE)
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      script: |
        #! /bin/sh

        echo "Run the below command to play:"
        echo "kubectl exec --stdin --tty -n $(params.NAMESPACE) ${POD_NAME} -- /bin/sh"
        echo ""
        echo -e "then type 'start'"

        i=0
        
        while [ "$i" -le 1 ]; do
            if [ -f end ]; then
                echo "you win :)"
                exit 0;
            fi
            if [ -f file ]; then
                echo "you lose :("
                exit 1;
            fi
            if [ -d skip ]; then
              echo ";)"
              exit 0;
            fi
        done
