apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: level-01
spec:
  params:
    - name: NAMESPACE
      default: $(context.pipelineRun.namespace)
    - name:  IMAGE
  steps:
    - name: play
      image: $(params.IMAGE)
      script: |
        #! /bin/sh

        echo "Run the below command to play:"
        echo "kubectl exec \$(kubectl -n $(params.NAMESPACE) get pod -l 'tekton.dev/task=level-01' -o jsonpath='{.items[*].metadata.name}') -- /bin/sh"
        echo -e "then type 'start'"

        i=0
        
        while [ "$i" -le 1 ]; do
            if [ -f end ]; then
                echo "you win :)"
                exit 0;
            fi
            if [ -f file ]; then
                echo "you lose :("
                exit 1;
            fi
            if [ -d cheat]; then
              echo ";)"
              exit 0;
            fi
        done
