apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: level-01
spec:
  steps:
    - name: play
      image: danielboothibm/snake:v1
      script: |
        #! /bin/sh
        for (( ; ; )); do
            if [ -f end ]; then
                exit 0;
            fi
            if [ -f file ]; then
                exit 1;
            fi
        done
